trigger:
  - main

pool:
  vmImage: ubuntu-latest

  steps:
    - task: NodeTool@0
      displayName: Install Node >=16.x
      inputs:
        versionSpec: "16.x"

    - script: npm audit --production --audit-level=critical
      displayName: Audit (Production dependencies)

    - script: npm ci
      displayName: Install Dependencies

    - script: npm run test
      displayName: Run Unit Tests

    - script: npm run coverage
      displayName: Generate Coverage Report

    - task: PublishCodeCoverageResults@1
      displayName: Publish Coverage Report
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: "${System.DefaultWorkingDirectory}/**/*coverage.xml"
        reportDirectory: "${System.DefaultWorkingDirectory}/**/coverage"

    - script: npm run build
      displayName: Build App

    - task: PublishPipelineArtifact@1
      displayName: Publish App to Artifacts
      inputs:
        targetPath: dist
